---
title: "Reproduction Analysis Plan"
author: "Alana Lutz"
date: "2023-10-05"
output: pdf_document
---

# Planned revisions to reproduction of Malcomb et al. 2014

Author: Alana Lutz

## Analysis

1) Modify the final vulnerability raster calculation from an additive aggregation to a geometric aggregation.
Additive aggregations assume that there is no interaction between indicators, which is often not the case with social vulnerability variables.
Additive aggregations may also increase compensability, in which a low value in one indicator can mask a high value in another.
Geometric aggregation can reduce issues with interaction and compensability.
2) Modify code to visualize all maps with tmap instead of ggplot2.
This change will improve the aesthetics and clarity of the maps for better communication of results.
3) Write discussion and conclusions section of report.

## Results

I will reproduce Fig. 5 using the geometric aggregation formula and compare the resulting map to the version of Fig. 5 produced using the additive aggregation formula.
I will also produce a map that subtracts the additive aggregation raster from the geometric aggregation raster for ease of comparison.

## Discussion

If the vulnerability map produced by a geometric aggregation is notably different from the map produced by an additive aggregation, it will mean that this social vulnerability analysis is sensitive to the specific method of mathematical aggregation.
Specifically, this result would suggest that there may be significant interaction between vulnerability indicators or compensability in the additive aggregation that should be accounted for.